devious/devious/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from devious.settings import MEDIA_ROOT
from django.views.static import serve
urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'',include('users.urls',namespace='users')),
    url(r'^project/',include('project.urls',namespace='project')),
    url(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT}),
    # url(r'^search/',include('haystack.urls')),
    url(r'^order/',include('order.urls',namespace='order')),
]

devious/order/urls.py
from django.conf.urls import url


urlpatterns = [

]

devious/users/urls.py
from django.conf.urls import url
from users import views
urlpatterns = [
	# 首页
	url(r'^$',views.IndexView.as_view(),name='index'),
	# 登录
	url(r'^login/$',views.UserLoginView.as_view(),name='login'),
	# 注册
	url(r'^register/$',views.UserRegisterView.as_view(),name='register'),
	# 注册激活
	url(r'^active/(?P<active_code>.*)',views.ActiveUserView.as_view(),name='active'),
	# 退出
	url(r'^logout/$',views.UserLogoutView.as_view(),name='logout'),

	# 发起众筹 1
	url(r'^ini1/$',views.InitiateView.as_view(),name='ini1'),
	url(r'^ini2/$', views.Initiate2View.as_view(), name='ini2'),
	url(r'^ini3/(?P<pro_id>.*)',views.AddGoods.as_view(),name='addgood'),
	url(r'^ini4/$',views.Initiate4View.as_view(),name='ini4'),
	url(r'^ini5/$',views.Initiate5View.as_view(),name='ini5'),
	url(r'^ini6/$',views.Initiate6View.as_view(),name='ini6'),
	# 用户中心
	url(r'^info/$',views.UserInfo.as_view(),name='info'),
	url(r'^mine/$',views.MyDevious.as_view(),name='mine'),
	url(r'^real/$',views.RealName.as_view(),name='real'),

]

devious/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from project.models import Project, Company


# Create your models here.


class UserProfile(AbstractUser):
	authstatus = models.SmallIntegerField(default=0, choices=((0, '未实名认证'), (1, '实名认证申请中'), (2, '已实名认证')),
										  verbose_name='用户状态', null=False)
	usertype = models.BooleanField(default=0, choices=((0, '个人'), (1, '企业')), verbose_name='用户类型', null=False)
	realname = models.CharField(max_length=255, verbose_name='真实姓名')

	class Meta:
		verbose_name = '用户信息表'
		verbose_name_plural = verbose_name


class EmailCode(models.Model):
	code = models.CharField(max_length=20, verbose_name='验证码')
	email = models.EmailField(verbose_name='邮箱', max_length=20)
	send_type = models.CharField(max_length=40,
								 choices=(('register', '注册'), ('forgot', '忘记密码'), ('update_email', '修改邮箱')),
								 verbose_name='验证码类型')
	send_time = models.DateField(default=datetime.now, verbose_name='发送时间')

	class Meta:
		verbose_name = '邮箱验证码'
		verbose_name_plural = verbose_name


class Banner(models.Model):
	project = models.ForeignKey(Project, null=True)
	name = models.CharField(max_length=20, verbose_name='轮播图')
	image = models.ImageField(upload_to='banner/%Y/%m', verbose_name='图片路径')
	url = models.URLField(verbose_name='链接')

	class Meta:
		verbose_name = '轮播图'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name


class UserSupprot(models.Model):
	user = models.ForeignKey(UserProfile, verbose_name='支持者')
	project = models.ForeignKey(Project, verbose_name='支持的项目')
	add_time = models.DateField(verbose_name='支持时间', default=datetime.now)

	class Meta:
		verbose_name = '用户支持'
		verbose_name_plural = verbose_name


class UserFlower(models.Model):
	user = models.ForeignKey(UserProfile, verbose_name='关注的人')
	company = models.ForeignKey(Project, verbose_name='关注的公司')
	add_time = models.DateField(verbose_name='关注的时间', default=datetime.now)

	class Meta:
		verbose_name = '用户关注'
		verbose_name_plural = verbose_name


class Address(models.Model):
	user = models.ForeignKey(UserProfile, verbose_name='用户')
	name = models.CharField(max_length=30, verbose_name='收货人', null=True)
	address = models.CharField(max_length=100, verbose_name='收货地址')
	phone = models.BigIntegerField(verbose_name='手机号码')

	class Meta:
		verbose_name = '收货地址'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.address


class UserCreate(models.Model):
	user = models.ForeignKey(UserProfile, verbose_name='创建项目的人')
	project = models.ForeignKey(Project, verbose_name='创建的项目')
	add_time = models.DateField(verbose_name='关注的时间', default=datetime.now)

	class Meta:
		verbose_name_plural = verbose_name = '创建项目表'

	def __str__(self):
		return self.user.username

devious/users/forms.py
from django import forms


# 用户登录表单验证
class UserLoginForm(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True)


# 用户注册表单验证
class UserRegisterForm(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True)
	email = forms.EmailField(required=True)


# 添加收货地址的表单验证
class AddressForm(forms.Form):
	name = forms.CharField(required=True)
	phone = forms.CharField(required=True,error_messages={'required':  "密码不能为空"})
	address = forms.CharField(required=True)


# 上传图片验证
class Upload(forms.Form):
	image_title = forms.FileField(required=False)
	image_detail = forms.FileField(required=False)


class Upload1(forms.Form):
	image = forms.FileField(required=False)

devious/users/views.py
import time
from datetime import datetime, timedelta

from django.shortcuts import render, redirect
from django.views.generic import View
from users.forms import UserRegisterForm, UserLoginForm, AddressForm
from users.models import UserProfile, EmailCode, Banner, Address, UserCreate, UserSupprot, UserFlower
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from users.send_email import send_register_email
from project.models import Tag, Label, Company, Project
from django.http import JsonResponse
from django.core.files.storage import default_storage
from devious.settings import MEDIA_ROOT
from users.forms import Upload, Upload1
from project.models import ReturnGoods, Invoice, Label


# Create your views here.


# 首页
class IndexView(View):
	def get(self, request):
		banners = Banner.objects.all()
		tags = Tag.objects.all()
		return render(request, 'index.html', {'banners': banners, 'tags': tags})


# 用户登录
class UserLoginView(View):
	def get(self, request):
		return render(request, 'users/login.html')

	def post(self, request):
		login_form = UserLoginForm(request.POST)

		if login_form.is_valid():
			username = request.POST.get('username')
			password = request.POST.get('password')
			remember = request.POST.get('remember')
			typess = request.POST.get('typess')
			if typess == 'member':
				is_staff = 0
			else:
				is_staff = 1
			user = authenticate(username=username, password=password)
			print('aaaaa')
			if user is not None:
				if user.is_active:
					login(request, user)
					print('------------>', user.is_staff, typess)
					if user.is_staff == True:
						if typess == 'user':
							return redirect(reverse('admin'))
						else:
							return redirect(reverse('users:index'))

					elif user.is_staff == False and typess == 'member':
						return redirect(reverse('users:index'))
					else:
						return render(request, 'users/login.html', {'msg': '没有权限'})
				else:
					return render(request, 'users/login.html', {'msg': '用户未激活，请去激活'})
			else:
				return render(request, 'users/login.html', {'msg': '用户名或密码错误'})
		else:
			return render(request, 'users/login.html', {'login_form': login_form})


# 用户注册
class UserRegisterView(View):
	def get(self, request):
		return render(request, 'users/reg.html')

	def post(self, request):
		register_form = UserRegisterForm(request.POST)
		if register_form.is_valid():
			username = request.POST.get('username')
			email = request.POST.get('email')
			if UserProfile.objects.filter(username=username):
				return render(request, 'users/reg.html', {'msg': '用户名已存在', 'register_form': register_form})
			if UserProfile.objects.filter(email=email):
				return render(request, 'users/reg.html', {'msg': '邮箱已存在', 'register_form': register_form})
			password = request.POST.get('password')

			types = request.POST.get('type')
			print(types)
			user = UserProfile()
			user.username = username
			user.password = make_password(password=password)
			user.email = email
			user.usertype = types
			user.is_active = 0
			user.save()
			send_register_email(email, send_type='register')
			return render(request, 'users/login.html')
		return render(request, 'users/reg.html', {'register_form': register_form})


# 注册激活
class ActiveUserView(View):
	def get(self, request, active_code):
		records = EmailCode.objects.filter(code=active_code)
		if records:
			for record in records:
				email = record.email
				user = UserProfile.objects.get(email=email)
				user.is_active = 1
				user.save()
			return redirect(reverse('users:login'))
		return render(request, 'users/active_fail.html')


# 用户登出
class UserLogoutView(View):
	def get(self, request):
		user = request.user
		if user:
			logout(request)
			return redirect(reverse('users:index'))


# 发起众筹
class InitiateView(View):
	def get(self, request):
		return render(request, 'users/start.html')


# 发起众筹2
class Initiate2View(View):
	def get(self, request):
		tags = Tag.objects.all()
		labels = Label.objects.all()
		context = {
			'tags': tags,
			'labels': labels,
		}
		return render(request, 'users/start-step-1.html', context=context)




class Initiate6View(View):
	def get(self, request):
		return render(request, 'users/start-step-2.html')

	def post(self, request):
		tag = request.POST.get('tag')
		print(tag)
		label = request.POST.getlist('labelname')
		print(type(label))
		print(label)
		label_str = ','.join(label)
		p_name = request.POST.get('p_name')

		p_desc = request.POST.get('p_desc')
		p_money = request.POST.get('p_money')

		p_time = request.POST.get('p_time')
		image_title = save_image(str(int(time.time())) + request.FILES['image_title'].name, request.FILES['image_title'])
		image_detail = save_image(str(int(time.time())) + request.FILES['image_detail'].name, request.FILES['image_detail'])

		u_name = request.POST.get('u_name')
		u_phone = request.POST.get('u_phone')
		u_c_phone = request.POST.get("u_c_phone")
		u_desc = request.POST.get("u_desc")
		now = datetime.now()
		aDay = timedelta(days=30)
		now = now + aDay
		project = Project()
		project.name = p_name
		project.desc = p_desc
		print(p_money)
		project.money = int(p_money)
		project.image1 = image_title
		project.image2 = image_detail
		project.tags = label_str
		tags = Tag.objects.get(name=tag)
		project.tag = tags
		project.date = now.strftime('%Y-%m-%d')
		project.time = int(p_time)
		# project.status = '即将开始'
		project.save()
		company = Company()
		company.name = u_name
		company.desc = u_desc
		company.phone = u_c_phone
		company.c_phone = int(u_phone)
		company.aut = '未认证'

		company.save()
		projects = Project.objects.get(name=p_name)
		usercreate = UserCreate()
		usercreate.user = request.user
		usercreate.project = projects
		usercreate.save()
		return JsonResponse({"res": '1'})

class Initiate4View(View):
	def get(self, request):
		return render(request, 'users/start-step-3.html')


class Initiate5View(View):
	def get(self, request):
		return render(request, 'users/start-step-4.html')


# 会员中心
class UserInfo(View):
	def get(self, request):
		user = request.user
		if user:
			return render(request, 'users/member.html')


# 我的众筹
class MyDevious(View):
	def get(self, request):
		_user = request.user

		supp_p = UserSupprot.objects.filter(user=_user)
		flow_p = UserFlower.objects.filter(user=_user)
		cre_p = UserCreate.objects.filter(user=_user)
		return render(request, 'users/minecrowdfunding.html',
					  {'s_projects': supp_p, 'f_projects': flow_p, 'c_projects': cre_p})


# 实名认证
class RealName(View):
	def get(self, request):
		return render(request, 'users/accttype.html')


# 认证申请
class Apply_real(View):
	def get(self, request):
		return render(request, 'users/')


def save_image(image_detail_filename, file_obj):
	# 一定要有uploadimage文件夹
	with default_storage.open(MEDIA_ROOT + '/' + 'uploadimage' + '/' + image_detail_filename,'wb+') as file:
		for chunk in file_obj.chunks():
			file.write(chunk)
	image_detail_upload = 'uploadimage/' + image_detail_filename
	return image_detail_upload


class AddGoods(View):
	def post(self, request, pro_id):
		print('进4了')
		form = Upload1(request.POST, request.FILES)
		if form.is_valid():
			typeS = request.POST.get('type')
			money = request.POST.get('money')
			image = form.cleaned_data['image']
			desc = request.POST.get('desc')
			num = request.POST.get('number')
			limit = request.POST.get('limit')
			freight = request.POST.get('freight')
			invioce = request.POST.get('ok')
			timea = request.POST.get('time')
			rg = ReturnGoods()
			rg.desc = desc
			rg.image = image
			rg.freight = int(freight)
			rg.number = int(num)
			rg.limit_purch = limit
			rg.return_goods_time = int(timea)
			rg.type = typeS
			rg.pay_money = money

			rg.invoice = '自定义发票'
			project1 = Project.objects.get(id=int(pro_id))
			rg.project = project1
			rg.save()

			return render(request, 'users/start-step-2.html', {'project': project1})

devious/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock extra_css %}
    {% block log%}
    {% endblock log %}
{% block content %}
    <div class="container">

      <form class="form-signin" role="form" method="post" action="{% url 'users:login' %}">
        <h2 class="form-signin-heading"><i class="glyphicon glyphicon-log-in"></i> 用户登录</h2>
		  <div class="form-group has-success has-feedback">
			<input type="text" class="form-control" name="username" id="inputSuccess4" placeholder="请输入登录账号" autofocus>
			<span class="glyphicon glyphicon-user form-control-feedback"></span>
		  </div>
		  <div class="form-group has-success has-feedback">
			<input type="password" class="form-control" name="password" id="inputSuccess3" placeholder="请输入登录密码" style="margin-top:10px;">
			<span class="glyphicon glyphicon-lock form-control-feedback"></span>
		  </div>
		  <div class="form-group has-success has-feedback">
			<select class="form-control" id="select" name="typess">
                <option value="member">会员</option>
                <option value="user">管理</option>
            </select>
		  </div>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me" name="remember"> 记住我
          </label>
          <br>
          <label>
            忘记密码
          </label>
          <label style="float:right">
            <a href="{% url 'users:register' %}">我要注册</a>
          </label>
        </div>
        <input class="btn btn-lg btn-success btn-block" type="submit" value="登录">
          {% for key,value in login_form.errors.items %}
              {{ value }}
          {% endfor %}
      {% if not login_form.errors %}{{ msg }}{% endif %}
          {% csrf_token %}
      </form>
    </div>
{#    <script src="/static/jquery/jquery-2.1.1.min.js"></script>#}
{#    <script src="/static/bootstrap/js/bootstrap.min.js"></script>#}
{#    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>#}
{#    <script>#}
{#        $(function () {#}
{#            $("#login").click(function () {#}
{#                 var username = $("#inputSuccess4").val();#}
{#                 var password = $("#inputSuccess3").val();#}
{#                 var typess = $("select").val();#}
{#                 var remember = $("input[name='remember']").prop('checked');#}
{#                 var csrf = $("input[name='csrfmiddlewaretoken']").val();#}
{#                 params = {#}
{#                     'username':username,#}
{#                     'password':password,#}
{#                     'typess':typess,#}
{#                     'remember':remember,#}
{#                     'csrfmiddlewaretoken':csrf,#}
{#                 };#}
{##}
{#                 $.post('{% url "users:login" %}',params,function(data){#}
{#                 if (data.res === 0){#}
{#                     console.log('aaa')#}
{#                 } else if(data.res === 1){#}
{#                     console.log('bbb')#}
{#                 }#}
{#             })#}
{##}
{##}
{#        });#}
{#        })#}
{##}
{#    </script>#}
{% endblock content %}
{% block footer %}
{% endblock footer %}
{% block extra_js %}
{% endblock extra_js %}

devious/templates/users/member.html
{% extends 'm_base.html' %}
{% load staticfiles %}
{% block extrac_style %}
    <style>
#footer {
    padding: 15px 0;
    background: #fff;
    border-top: 1px solid #ddd;
    text-align: center;
}
#topcontrol {
  color: #fff;
  z-index: 99;
  width: 30px;
  height: 30px;
  font-size: 20px;
  background: #222;
  position: relative;
  right: 14px !important;
  bottom: 11px !important;
  border-radius: 3px !important;
}

#topcontrol:after {
  /*top: -2px;*/
  left: 8.5px;
  content: "\f106";
  position: absolute;
  text-align: center;
  font-family: FontAwesome;
}

#topcontrol:hover {
    color: #fff;
    background: #18ba9b;
    -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
    -o-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
}

	</style>
{% endblock extrac_style %}
{% block content %}
    <div class="col-sm-9 col-md-9 column">
        <blockquote style="border-left: 5px solid #f60;color:#f60;padding: 0 0 0 20px;">
                                        <b>
                                            我的钱包
                                        </b>
                                    </blockquote>
            <div id="main" style="width: 600px;height:400px;"></div>
            <blockquote style="border-left: 5px solid #f60;color:#f60;padding: 0 0 0 20px;">
                                        <b>
                                            理财
                                        </b>
                                    </blockquote>
            <div id="main1" style="width: 600px;height:400px;"></div>
            <blockquote style="border-left: 5px solid #f60;color:#f60;padding: 0 0 0 20px;">
                                        <b>
                                            比例
                                        </b>
                                    </blockquote>
            <div id="main2" style="width: 600px;height:400px;"></div>
		</div>
{% endblock content %}

devious/templates/users/reg.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock extra_css %}
    {% block log%}
    {% endblock log %}
{% block content %}
    <div class="container">

      <form class="form-signin" role="form" method="post" action="{% url 'users:register' %}">
        <h2 class="form-signin-heading"><i class="glyphicon glyphicon-log-in"></i> 用户注册</h2>
		  <div class="form-group has-success has-feedback">
			<input type="text" class="form-control" name="username" id="inputSuccess4" placeholder="请输入登录账号" autofocus>
			<span class="glyphicon glyphicon-user form-control-feedback"></span>
		  </div>
		  <div class="form-group has-success has-feedback">
			<input type="password" class="form-control" name="password" id="inputSuccess4" placeholder="请输入登录密码" style="margin-top:10px;">
			<span class="glyphicon glyphicon-lock form-control-feedback"></span>
		  </div>
		  <div class="form-group has-success has-feedback">
			<input type="text" class="form-control" name="email" id="inputSuccess4" placeholder="请输入邮箱地址" style="margin-top:10px;">
			<span class="glyphicon glyphicon glyphicon-envelope form-control-feedback"></span>
		  </div>
		  <div class="form-group has-success has-feedback">
			<select class="form-control" name="type">
                <option value="0">企业</option>
                <option value="1">个人</option>
            </select>
		  </div>
        <div class="checkbox">
          <label>
            忘记密码
          </label>
          <label style="float:right">
            <a href="{% url 'users:login' %}">我有账号</a>
          </label>
        </div>
        <input class="btn btn-lg btn-success btn-block" type="submit" value="注册">
          {% for key,value in register_form.errors.items %}
          {% if register_form.errors %}{{ value }}{% else %}{{ msg }}{% endif %}
          {% endfor %}
          {% csrf_token %}
      </form>
    </div>
    <script src="/static/jquery/jquery-2.1.1.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
{% endblock content %}
{% block footer %}
{% endblock footer %}

devious/templates/users/start-step-3.html
{% extends 'p_base.html' %}
{% load staticfiles %}
{% block extra_style %}
	<style>
#footer {
    padding: 15px 0;
    background: #fff;
    border-top: 1px solid #ddd;
    text-align: center;
}
#topcontrol {
  color: #fff;
  z-index: 99;
  width: 30px;
  height: 30px;
  font-size: 20px;
  background: #222;
  position: relative;
  right: 14px !important;
  bottom: 11px !important;
  border-radius: 3px !important;
}

#topcontrol:after {
  /*top: -2px;*/
  left: 8.5px;
  content: "\f106";
  position: absolute;
  text-align: center;
  font-family: FontAwesome;
}

#topcontrol:hover {
    color: #fff;
    background: #18ba9b;
    -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
    -o-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
}

.label-type, .label-status, .label-order {
    background-color: #fff;
    color: #f60;
    padding : 5px;
    border: 1px #f60 solid;
}
#typeList  :not(:first-child) {
    margin-top:20px;
}
.label-txt {
    margin:10px 10px;
    border:1px solid #ddd;
    padding : 4px;
    font-size:14px;
}
.panel {
    border-radius:0;
}

.progress-bar-default {
    background-color: #ddd;
}
	</style>
{% endblock extra_style %}

{% block content %}
        
        
        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="panel panel-default" >
                        <div class="panel-heading" style="text-align:center;">
                            <div class="container-fluid">
                                <div class="row clearfix">
                                    <div class="col-md-3 column">
                                        <div class="progress" style="height:50px;border-radius:0;    position: absolute;width: 75%;right:49px;">
                                          <div class="progress-bar progress-bar-default" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;height:50px;">
                                            <div style="font-size:16px;margin-top:15px;">1. 项目及发起人信息</div>
                                          </div>
                                        </div>
                                        <div style="right: 0;border:10px solid #ddd;border-left-color: #88b7d5;border-width: 25px;position: absolute;
                                             border-left-color: rgba(221, 221, 221, 1);
                                             border-top-color: rgba(221, 221, 221, 0);
                                             border-bottom-color: rgba(221, 221, 221, 0);
                                             border-right-color: rgba(221, 221, 221, 0);
                                        ">
                                        </div>
                                    </div>
                                    <div class="col-md-3 column">
                                        <div class="progress" style="height:50px;border-radius:0;position: absolute;width: 75%;right:49px;">
                                          <div class="progress-bar progress-bar-default" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;height:50px;">
                                            <div style="font-size:16px;margin-top:15px;">2. 回报设置</div>
                                          </div>
                                        </div>
                                        <div style="right: 0;border:10px solid #ddd;border-left-color: #88b7d5;border-width: 25px;position: absolute;
                                             border-left-color: rgba(221, 221, 221, 1);
                                             border-top-color: rgba(221, 221, 221, 0);
                                             border-bottom-color: rgba(221, 221, 221, 0);
                                             border-right-color: rgba(221, 221, 221, 0);
                                        ">
                                        </div>
                                    </div>
                                    <div class="col-md-3 column">
                                        <div class="progress" style="height:50px;border-radius:0;position: absolute;width: 75%;right:49px;">
                                          <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;height:50px;">
                                            <div style="font-size:16px;margin-top:15px;">3. 确认信息</div>
                                          </div>
                                        </div>
                                        <div style="right: 0;border:10px solid #ddd;border-left-color: #88b7d5;border-width: 25px;position: absolute;
                                             border-left-color: rgba(92, 184, 92, 1);
                                             border-top-color: rgba(92, 184, 92, 0);
                                             border-bottom-color: rgba(92, 184, 92, 0);
                                             border-right-color: rgba(92, 184, 92, 0);
                                        ">
                                        </div>
                                    </div>
                                    <div class="col-md-3 column">
                                        <div class="progress" style="height:50px;border-radius:0;">
                                          <div class="progress-bar progress-bar-default" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 100%;height:50px;">
                                            <div style="font-size:16px;margin-top:15px;">4. 完成</div>
                                          </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-body">
                        
                        <div class="container-fluid">
                            <div class="row clearfix">
                                <div class="col-md-12 column">
                                    <blockquote style="border-left: 5px solid #f60;color:#f60;padding: 0 0 0 20px;">
                                        <b>
                                            确认信息（请填写易付宝企业账号用于收款及身份核实）
                                        </b>
                                    </blockquote>
                                </div>
                                <div class="col-md-12 column">
                                
                                
                                    <div class="row clearfix">
                                        <div class="col-md-6 column">
                                            <form role="form">
                                                <div class="form-group">
                                                     <label for="exampleInputEmail1">易付宝企业账号：</label><input type="email" class="form-control" id="exampleInputEmail1" />
                                                </div>
                                                <div class="form-group">
                                                     <label for="exampleInputPassword1">法人身份证号：</label><input type="password" class="form-control" id="exampleInputPassword1" />
                                                </div>
                                            </form>
                                        </div>
                                        <div class="col-md-6 column">
                                            <div class="panel panel-default">
                                                <div class="panel-body" style="padding:40px;">
                                                    <i class="glyphicon glyphicon-user"></i> 易购账户名：18801282948<br><br><span style="margin-left:60px;">您正在使用该账号发起众筹项目</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                        <div class="panel-footer" style="text-align:center;">
                            <button type="button" class="btn  btn-default btn-lg" onclick="window.location.href='{% url 'users:ini2' %}'">上一步</button>
                            <button type="button" class="btn  btn-warning btn-lg" onclick="window.location.href='{% url 'users:ini5' %}'">提交</button>
                            <a class="btn" > 保存草稿 </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
{% endblock content %}