devious/devious/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from devious.settings import MEDIA_ROOT
from django.views.static import serve
urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'',include('users.urls',namespace='users')),
    url(r'^project/',include('project.urls',namespace='project')),
    url(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT}),
    # url(r'^search/',include('haystack.urls')),
    url(r'^order/',include('order.urls',namespace='order')),
]

devious/order/urls.py
from django.conf.urls import url


urlpatterns = [

]

devious/project/urls.py
from django.conf.urls import url
from project import views


urlpatterns = [
	url(r'^list/$',views.ProjectListView.as_view(),name='list'),
	url(r'^detail/(?P<p_id>.*)',views.ProjectDetailView.as_view(),name='detail'),
	url(r'^fav/$',views.AddFavView.as_view(),name='fav'),
	url(r'^pay/$',views.SupportView.as_view(),name='pay'),
	url(r'^gopay/$',views.GoPayView.as_view(),name='go_pay'),

]

devious/users/urls.py
from django.conf.urls import url
from users import views
urlpatterns = [
	# 首页
	url(r'^$',views.IndexView.as_view(),name='index'),
	# 登录
	url(r'^login/$',views.UserLoginView.as_view(),name='login'),
	# 注册
	url(r'^register/$',views.UserRegisterView.as_view(),name='register'),
	# 注册激活
	url(r'^active/(?P<active_code>.*)',views.ActiveUserView.as_view(),name='active'),
	# 退出
	url(r'^logout/$',views.UserLogoutView.as_view(),name='logout'),

	# 发起众筹 1
	url(r'^ini1/$',views.InitiateView.as_view(),name='ini1'),
	url(r'^ini2/$', views.Initiate2View.as_view(), name='ini2'),
	url(r'^ini3/(?P<pro_id>.*)',views.AddGoods.as_view(),name='addgood'),
	url(r'^ini4/$',views.Initiate4View.as_view(),name='ini4'),
	url(r'^ini5/$',views.Initiate5View.as_view(),name='ini5'),
	url(r'^ini6/$',views.Initiate6View.as_view(),name='ini6'),
	# 用户中心
	url(r'^info/$',views.UserInfo.as_view(),name='info'),
	url(r'^mine/$',views.MyDevious.as_view(),name='mine'),
	url(r'^real/$',views.RealName.as_view(),name='real'),

]

devious/project/models.py
from django.db import models
from datetime import datetime


# Create your models here.


class Tag(models.Model):
	name = models.CharField(max_length=100, verbose_name='类别名称')

	class Meta:
		verbose_name = '项目类别'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name


class Project(models.Model):
	name = models.CharField(max_length=255, verbose_name='项目名称')
	desc = models.CharField(max_length=255, verbose_name='项目描述')
	follower = models.IntegerField(verbose_name='关注人数', default=0)
	money = models.BigIntegerField(verbose_name='钱')
	supportmoney = models.BigIntegerField(verbose_name='支持的金额', null=True, default=0)
	time = models.IntegerField(verbose_name='筹集时间', null=True)
	date = models.DateField(verbose_name='截止日期')
	image1 = models.ImageField(max_length=200, upload_to='image/%Y/%m', verbose_name='项目图片1', null=True)
	image2 = models.ImageField(max_length=200, upload_to='image/%Y/%m', verbose_name='项目图片2', null=True)
	status = models.SmallIntegerField(default=0, choices=((0, '即将开始'), (1, '众筹中'), (2, '众筹成功'), (3, '众筹失败')),
									  verbose_name='项目状态')
	createdate = models.DateField(verbose_name='创建项目的时间', default=datetime.now)
	supporter = models.IntegerField(verbose_name='支持人数', null=True, default=0)
	tag = models.ForeignKey(Tag, verbose_name='类别')
	company = models.ForeignKey('Company', null=True)
	returns = models.CharField(max_length=255, verbose_name='回报内容', null=True)
	tags = models.CharField(max_length=100, verbose_name='项目标签', null=True)

	class Meta:
		verbose_name = '众筹项目'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name

	def get_time(self):
		endtime = self.date.strftime('%Y-%m_%d')
		endtime = datetime.strptime(endtime, '%Y-%m_%d')
		now = datetime.now().strftime('%Y-%m_%d')
		now = datetime.strptime(now, '%Y-%m_%d')

		left_time = (endtime - now).days
		if left_time > 0:
			self.status = 1
		elif left_time <= 0:
			if self.supportmoney >= self.money:
				self.status = 2
			else:
				self.status = 3
		return left_time


# 公司
class Company(models.Model):
	name = models.CharField(max_length=60, verbose_name='公司名称')
	desc = models.CharField(max_length=255, verbose_name='公司简介')
	c_phone = models.CharField(max_length=20, verbose_name='电话', null=True)
	phone = models.IntegerField(verbose_name='客服电话')
	image = models.ImageField(upload_to='company/%Y/%m', null=True, verbose_name='公司图片')
	aut = models.CharField(max_length=100, choices=((('0', '未认证'), ('1', '已认证'))), verbose_name='认证状态', default='0',
						   null=True)

	class Meta:
		verbose_name = '公司名称'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name

# 发票
class Invoice(models.Model):
	types = models.CharField(choices=(('0', '无发票'), ('1', '个人发票'), ('2', '自定义发票')), verbose_name='发票', max_length=20)

	def __str__(self):
		return 'Invoice'


class ReturnGoods(models.Model):
	project = models.ForeignKey(Project, verbose_name='项目名称')
	type = models.CharField(max_length=20, choices=(('0', '实物回报'), ('1', '虚拟物品回报')), verbose_name='回报类型', default='0')
	desc = models.CharField(max_length=100, verbose_name='回报简述', null=True)
	image = models.ImageField(upload_to='return/%Y/%m', verbose_name='回报图片', null=True)
	number = models.IntegerField(verbose_name='回报数量', null=True)
	pay_money = models.BigIntegerField(verbose_name='支付金额')
	palces = models.CharField(max_length=10, verbose_name='名额', default='无限制')
	limit_purch = models.CharField(max_length=20, verbose_name='单笔限购', default='不限购')
	return_goods_time = models.IntegerField(verbose_name='回报时间')
	freight = models.IntegerField(default=0, verbose_name='运费')
	invoice = models.CharField(max_length=20, choices=(('0', '无发票'), ('1', '个人发票'), ('2', '自定义发票')), verbose_name='发票')

	class Meta:
		verbose_name = '回报'
		verbose_name_plural = verbose_name

	def __str__(self):
		return 'aaa'


class Label(models.Model):
	name = models.CharField(max_length=20, verbose_name='标签名字')
	project = models.ForeignKey(Project, verbose_name='项目名称', null=True)

	class Meta:
		verbose_name = '标签'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name

devious/project/views.py
from django.shortcuts import render
from django.views.generic import View
from project.models import Tag, Project
from pure_pagination import Paginator, PageNotAnInteger
from users.models import UserFlower,Address
from django.http import HttpResponse
import json
from project.models import Company
from users.models import UserProfile
from django.db.models import Q
from django.http import JsonResponse

# Create your views here.


class ProjectListView(View):
	def get(self, request):
		current_page = 'overview'
		project_list = Project.objects.all()
		tags = Tag.objects.all()
		search_keywords = request.GET.get('keywords')
		print(search_keywords,'-------------------')
		if search_keywords:
			project_list = Project.objects.filter(
				Q(name__icontains=search_keywords)
			)
		sort = request.GET.get('sort', '')
		if sort:
			tag = Tag.objects.get(id=int(sort))
			project_list = tag.project_set.all()
		status = request.GET.get('status', '')

		if status:
			project_list = Project.objects.filter(status=int(status))
		sorts = request.GET.get('sorts', '')
		if sorts:
			if sorts == 0:
				project_list = Project.objects.all().order_by('')
			elif sorts == 1:
				project_list = Project.objects.all().order_by('-money')
			elif sorts == 2:
				project_list = Project.objects.all().order_by('-supporter')

		project_nums = project_list.count()
		try:
			page = request.GET.get('page', 1)
		except PageNotAnInteger:
			page = 1

		p = Paginator(project_list, 1, request=request)

		project_list = p.page(page)
		return render(request, 'project/projects.html', {'projects': project_list, 'current_page': current_page,
														 'project_nums': project_nums,
														 'tag_list': tags,
														 'sort': sort,
														 'status': status,
														 'sorts': sorts,
														 })


# 项目详情页
class ProjectDetailView(View):
	def get(self, request, p_id):
		pro = Project.objects.get(id=p_id)
		fav_com = False
		if pro:
			if UserFlower.objects.filter(user=request.user, company=pro.id):
				fav_com = True
			fav_user = UserFlower.objects.filter(company=pro.id)
			num = len([fav.user for fav in fav_user])
			return_goods = pro.returngoods_set.all()
			return render(request, 'project/project.html', {'project': pro, 'fav_com': fav_com, 'num': num,'return_goods':return_goods})


# 关注公司
class AddFavView(View):
	def post(self, request):
		project_id = request.POST.get('fav_id')
		company = Company.objects.get(id=project_id)
		res = dict()
		if not request.user.is_authenticated():
			res['status'] = 'fail'
			res['msg'] = '用户未登陆'
			return HttpResponse(json.dumps(res), content_type='application/json')
		fav = UserFlower.objects.filter(user=request.user, company=int(project_id))
		if fav:
			fav.delete()
			res['status'] = 'success'
			res['msg'] = '关注'
		else:
			if company:
				user_fav = UserFlower()
				user_fav.user = request.user
				user_fav.company = company
				user_fav.save()
				res['status'] = 'success'
				res['msg'] = '已关注'
			else:
				res['status'] = 'fail'
				res['msg'] = '关注失败'

		return HttpResponse(json.dumps(res), content_type='application/json')


class SupportView(View):
	def get(self, request):
		p_id = request.GET.get('id')
		mon = request.GET.get('mon')
		project = Project.objects.get(id=p_id)

		return render(request, 'project/pay-step-1.html', {
			'project': project,
			'money': mon,
		})


# 去结算
class GoPayView(View):
	def get(self, request):
		p_id = request.GET.get('id')
		mon = request.GET.get('mon')
		project = Project.objects.get(id=p_id)
		return render(request, 'project/pay-step-2.html',{
			'project': project,
			'money': mon,
		})


	def post(self,request):
			name = request.POST.get('name')
			phone = request.POST.get('phone')
			address1 = request.POST.get('address')
			address2 = Address()
			address2.name = name
			address2.user = request.user
			address2.phone = phone
			address2.address = address1
			address2.save()

			return JsonResponse({'res':1})

devious/templates/project/project.html
{% extends 'p_base.html' %}
{% load staticfiles %}
{% block extra_style %}
	<style>
#footer {
    padding: 15px 0;
    background: #fff;
    border-top: 1px solid #ddd;
    text-align: center;
}
#topcontrol {
  color: #fff;
  z-index: 99;
  width: 30px;
  height: 30px;
  font-size: 20px;
  background: #222;
  position: relative;
  right: 14px !important;
  bottom: 11px !important;
  border-radius: 3px !important;
}

#topcontrol:after {
  /*top: -2px;*/
  left: 8.5px;
  content: "\f106";
  position: absolute;
  text-align: center;
  font-family: FontAwesome;
}

#topcontrol:hover {
    color: #fff;
    background: #18ba9b;
    -webkit-transition: all 0.3s ease-in-out;
    -moz-transition: all 0.3s ease-in-out;
    -o-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
}
.nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {
    border-bottom-color: #ddd;
}
.nav-tabs>li>a {
    border-radius: 0;
}
	</style>
{% endblock extra_style %}
{% block content %}
        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="jumbotron nofollow" style="    padding-top: 10px;">
                        <h3>
                            {{ project.name }}
                        </h3>
                        <div style="float:left;width:70%;">
                            {{ project.desc }}
                        </div>
                        <div style="float:right;">
                            <button type="button" id = 'bnn' data-fav-type="{{ project.company.id }}" class="btn btn-default"><i style="color:#f60" class="glyphicon glyphicon-heart"></i>{% if fav_com %} 已关注{% else %} 关注{% endif %}{{ num }}</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="row clearfix">
                        <div class="col-md-8 column">
                            <img alt="140x140" width="740" src="{{ MEDIA_URL }}{{ project.image1 }}" />
                            <img alt="140x140" width="740" src="{{ MEDIA_URL }}{{ project.image2 }}" />

                        </div>
                        <div class="col-md-4 column">
                            <div class="panel panel-default" style="border-radius: 0px;">
                                <div class="panel-heading" style="background-color: #fff;border-color: #fff;">
                                    <span class="label label-success"><i class="glyphicon glyphicon-tag"></i> {{ project.get_status_display }}</span>
                                </div>
                                <div class="panel-body">
                                    <h3 >
                                        已筹资金：￥{{ project.supportmoney }}
                                    </h3>
                                    <p><span>目标金额 ： {{ project.money }}.00</span><span style="float:right;">达成 ： {% widthratio project.money project.supportmoney 10 %}%</span></p>
                                    <div class="progress" style="height:10px; margin-bottom: 5px;">
                                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                                    </div>
                                    <p>剩余 {{ project.get_time }} 天</p>
                                    <div>
                                        <p><span>已有{{ project.supporter }}人支持该项目</span></p>
                                     <button type="button" class="btn  btn-warning btn-lg btn-block" data-toggle="modal" data-target="#myModal">立即支持</button>
                                    </div>
                                </div>
                                <div class="panel-footer" style="    background-color: #fff;
                                    border-top: 1px solid #ddd;
                                    border-bottom-right-radius: 0px;
                                    border-bottom-left-radius: 0px;">
                                <div class="container-fluid">
                                    <div class="row clearfix">
                                        <div class="col-md-3 column" style="padding:0;">
                                <img alt="140x140" src="{{ MEDIA_URL }}{{ project.company.image }}" data-holder-rendered="true" style="width: 80px; height: 80px;">
                                </div>
                                <div class="col-md-9 column">
                                    <div class="">
                                        <h4>
                                            <b>{{ project.company.name }}</b> <span style="float:right;font-size:12px;" class="label label-success">已认证</span>
                                        </h4>
                                        <p style="font-size:12px">
                                            {{ project.company.desc }}

                                        </p>
                                        <p style="font-size:12px">
                                        客服电话:0595-{{ project.company.phone }}
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                            {% for good in return_goods %}
					<div class="panel panel-default" style="border-radius: 0px;">
						<div class="panel-heading">
							<h3 >
								￥{{ good.pay_money }}.00 <span style="float:right;font-size:12px;">{{ good.palces }}，{{ good.project.supporter }}位支持者</span>
							</h3>
						</div>
						<div class="panel-body">
                            <p>配送费用：{{ good.freight }}</p>
                            <p>预计发放时间：项目筹款成功后的{{ good.return_goods_time }}天内</p>
                            <button type="button" class="btn  btn-warning btn-lg" onclick="window.location.href='/project/pay/?id={{ project.id }}&mon={{ good.pay_money }}'">支持</button>
                            <br><br>
                            <p>{{ good.desc }}）。</p>
						</div>
					</div>
{% endfor %}

                    <div><h2>为你推荐</h2><hr></div>
					<div class="prjtip panel panel-default" style="border-radius: 0px;">
						<div class="panel-body">
                            <img src="img/product-3.png" width="100%" height="100%">
						</div>
					</div>

					<div class="prjtip panel panel-default" style="border-radius: 0px;">
						<div class="panel-body">
                            <img src="img/product-4.jpg" width="100%" height="100%">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>







    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
      <div class="modal-dialog "  style="width:960px;height:400px;" role="document">
        <div class="modal-content" data-spy="scroll" data-target="#myScrollspy">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">选择支持项</h4>
          </div>
          <div class="modal-body">
<div class="container-fluid">
	<div class="row clearfix">
		<div class="col-sm-3 col-md-3 column" id="myScrollspy">
            <ul class="nav nav-tabs nav-stacked">
                {% for good in return_goods %}
                <li class="active"><a href="#section-1">￥{{ good.pay_money }}.00</a></li>
                {% endfor %}
            </ul>
		</div>
		<div id="navList" class="col-sm-9 col-md-9 column" style="height:400px;overflow-y:auto;">
            {% for good in return_goods %}
            <h2 id="section-1" style="border-bottom:1px dashed #ddd;" ><span style="font-size:20px;font-weight:bold;">￥{{ good.pay_money }}.00</span><span style="font-size:12px;margin-left:60px;">{{ good.palces }}，{{ good.project.supporter }}位支持者</span></h2>
            <p>配送费用：全国{{ good.freight }}</p>
            <p>预计发放时间：项目筹款成功后的{{ good.return_goods_time }}天内</p>
            <button type="button" class="btn  btn-warning btn-lg " onclick="window.location.href='/project/pay/?id={{ project.id }}&mon={{ good.pay_money }}'">支持</button>
            <br><br>
            <p>{{ good.desc }}</p>
            <hr>
            {% endfor %}
            </div>
        </div>
	</div>
</div>
          </div>
        </div>
      </div>
{% endblock content %}

{% block extra_js %}
	<script>
    $(".prjtip img").css("cursor", "pointer");
    $(".prjtip img").click(function(){
        window.location.href = 'project.html';
    });
	</script>
 <script>
       function add_fav(current_elem, fav_id) {

        $.ajax({
            cache: false,
            type: "POST",
            url: "{% url 'project:fav' %}",
            data: {'fav_id': fav_id},
            async: true,
            beforeSend: function (xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function (data) {
                if (data.status == 'fail') {
                    if (data.msg == '用户未登录') {
                        window.location.href = "{% url 'users:login' %}";
                    } else {
                        alert(data.msg)
                    }

                } else if (data.status == 'success') {
                    current_elem.text(data.msg)
                }
            },
        });
    }
    $("#bnn").click(function () {
        var type = $(this).attr('data-fav-type');
        add_fav($(this),type)
    })
 </script>
{% endblock extra_js %}

devious/templates/project/projects.html
{% extends 'p_base.html' %}
{% load staticfiles %}
{% block extra_style %}
    <style>
        #footer {
            padding: 15px 0;
            background: #fff;
            border-top: 1px solid #ddd;
            text-align: center;
        }

        #topcontrol {
            color: #fff;
            z-index: 99;
            width: 30px;
            height: 30px;
            font-size: 20px;
            background: #222;
            position: relative;
            right: 14px !important;
            bottom: 11px !important;
            border-radius: 3px !important;
        }

        #topcontrol:after {
            /*top: -2px;*/
            left: 8.5px;
            content: "\f106";
            position: absolute;
            text-align: center;
            font-family: FontAwesome;
        }

        #topcontrol:hover {
            color: #fff;
            background: #18ba9b;
            -webkit-transition: all 0.3s ease-in-out;
            -moz-transition: all 0.3s ease-in-out;
            -o-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
        }

        .label-type, .label-status, .label-order {
            background-color: #fff;
            color: #f60;
            padding: 5px;
            border: 1px #f60 solid;
        }

        #typeList :not(:first-child) {
            margin-top: 20px;
        }

        .label-text {
            margin: 0 10px;
        }

        .panel {
            border-radius: 0;
        }

        h3.break {
            font-size: 16px;
            display: block;
            white-space: nowrap;
            word-wrap: normal;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        h3.break > a {
            text-decoration: none;
        }
    </style>
{% endblock %}
{% block content %}





        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <ul id="typeList" style="list-style: none;">
                                <li>
                                    分类：<a class="{% ifequal sort '' %}label-type active{% endifequal %}"
                                          href="?status={{ status }}&sorts={{ sorts }}">全部</a>
                                    {% for tag in tag_list %}
                                        <a class="{% ifequal sort tag.id|stringformat:"i" %}label-type active{% else %}label-text{% endifequal %}"
                                           href="?sort={{ tag.id }}&status={{ status }}&sorts={{ sorts }}">{{ tag.name }}</a>{% endfor %}
                                </li>
                                <li>
                                    状态：<a class="{% ifequal status '' %}label-status{% endifequal %} actvie"
                                          href="?sort={{ sort }}&sorts={{ sorts }}">全部</a> <a
                                        class="{% ifequal status '0' %}label-status active{{ else }}label-text{% endifequal %}"
                                        href="?sort={{ sort }}&status=0&sorts={{ sorts }}">即将开始</a> <a
                                        class="{% ifequal status '1' %}label-status active{{ else }}label-text{% endifequal %}"
                                        href="?sort={{ sort }}&status=1&sorts={{ sorts }}">众筹中</a> <a
                                        class="{% ifequal status '2' %}label-status active{{ else }}label-text{% endifequal %}"
                                        href="?sort={{ sort }}&status=2&sorts={{ sorts }}">众筹成功</a>
                                </li>
                                <li>
                                    排序：<a class="{% ifequal sorts '' %}label-order active{% endifequal %}"
                                          href="?sort={{ sort }}&status={{ status }}">综合排序</a> <a
                                        class="{% ifequal sorts '0' %}label-order active{{ else }}label-text{% endifequal %}"
                                        href="?sort={{ sort }}&status={{ status }}&sorts=0">最新上线</a> <a
                                        class="{% ifequal sorts '1' %}label-order active{{ else }}label-text{% endifequal %}"
                                        href="?sort={{ sort }}&status={{ status }}&sorts=1">金额最多</a> <a
                                        class="{% ifequal sorts '2' %}label-order active{{ else }}label-text{% endifequal %}"
                                        href="?sort={{ sort }}&status={{ status }}&sorts=2">支持最多</a>
                                </li>
                            </ul>
                        </div>
                        <div class="panel-footer" style="height:50px;padding:0;">
                            <div style="float:left;padding:15px;">
                                共{{ project_nums }}个众筹项目
                            </div>
                            <div style="float:right;">
                                <div class="navbar-form navbar-left" role="search">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="请输入搜索内容" id="cont">
                                    </div>
                                    <button class="btn btn-default" id="search"><i
                                            class="glyphicon glyphicon-search"></i> 搜索
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div class="row">
                        {% for tags in projects.object_list %}
                            <div class="col-md-3">
                                <div class="thumbnail">
                                    <img alt="300x200" src="{{ MEDIA_URL }}{{ tags.image1 }}"/>
                                    <div class="caption">
                                        <h3 class="break">
                                            <a href="{% url 'project:detail' tags.id %}">{{ tags.name }}</a>
                                        </h3>
                                        <p>
                                        <div style="float:left;"><i class="glyphicon glyphicon-screenshot"
                                                                    title="目标金额"></i> ${{ tags.money }} </div>
                                        <div style="float:right;"><i title="截至日期"
                                                                     class="glyphicon glyphicon-calendar"></i> {{ tags.date }}
                                        </div>
                                        </p>
                                        <br>
                                        <div class="progress" style="margin-bottom: 4px;">
                                            <div class="progress-bar progress-bar-success" role="progressbar"
                                                 aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"
                                                 style="width: {% widthratio tags.money tags.supportmoney 10 %}%">
                                                <span>{% widthratio tags.money tags.supportmoney 10 %}% </span>
                                            </div>
                                        </div>
                                        <div><span style="float:right;"><i
                                                class="glyphicon glyphicon-star-empty"></i></span> <span><i
                                                class="glyphicon glyphicon-user"
                                                title="支持人数"></i> {{ tags.supporter }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>

        <!-- 分页器  -->
        <div class="container">
            <div class="row clearfix">
                <div class="col-md-12 column" style="text-align:center">
                    <ul class="pagination">
                        {% if projects.has_previous %} <!--判断前面是否有页数-->
                            <li class="long"><a href="?{{ projects.previous_page_number.querystring }}">上一页</a></li>
                        {% endif %}

                        {% for page in projects.pages %} <!--找出当前页-->
                            {% if page %}
                                {% ifequal page projects.number %}
                                    <li class="active"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="none"><a href="">...</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if projects.has_next %} <!--判断后面是否有页数-->
                            <li class="long"><a href="?{{ projects.next_page_number.querystring }}">下一页</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script src="http://cdn.static.runoob.com/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>
        $(function () {
            $('#search').on('click', function () {
                keywards = $("#cont").val();
                {#alert(keywards);#}
                request_url = '/project/list/?keywords=' + keywards;
                {#alert(request_url)#}
                window.location.href = request_url
            })
        })
    </script>
{% endblock content %}