devious/devious/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from devious.settings import MEDIA_ROOT
from django.views.static import serve
urlpatterns = [
    url(r'^admin/', admin.site.urls,name='admin'),
    url(r'',include('users.urls',namespace='users')),
    url(r'^project/',include('project.urls',namespace='project')),
    url(r'^media/(?P<path>.*)$',serve,{"document_root":MEDIA_ROOT}),
    # url(r'^search/',include('haystack.urls')),
    url(r'^order/',include('order.urls',namespace='order')),
]

devious/order/urls.py
from django.conf.urls import url


urlpatterns = [

]

devious/project/urls.py
from django.conf.urls import url
from project import views


urlpatterns = [
	url(r'^list/$',views.ProjectListView.as_view(),name='list'),
	url(r'^detail/(?P<p_id>.*)',views.ProjectDetailView.as_view(),name='detail'),
	url(r'^fav/$',views.AddFavView.as_view(),name='fav'),
	url(r'^pay/$',views.SupportView.as_view(),name='pay'),
	url(r'^gopay/$',views.GoPayView.as_view(),name='go_pay'),

]

devious/users/urls.py
from django.conf.urls import url
from users import views
urlpatterns = [
	# 首页
	url(r'^$',views.IndexView.as_view(),name='index'),
	# 登录
	url(r'^login/$',views.UserLoginView.as_view(),name='login'),
	# 注册
	url(r'^register/$',views.UserRegisterView.as_view(),name='register'),
	# 注册激活
	url(r'^active/(?P<active_code>.*)',views.ActiveUserView.as_view(),name='active'),
	# 退出
	url(r'^logout/$',views.UserLogoutView.as_view(),name='logout'),

	# 发起众筹 1
	url(r'^ini1/$',views.InitiateView.as_view(),name='ini1'),
	url(r'^ini2/$', views.Initiate2View.as_view(), name='ini2'),
	url(r'^ini3/(?P<pro_id>.*)',views.AddGoods.as_view(),name='addgood'),
	url(r'^ini4/$',views.Initiate4View.as_view(),name='ini4'),
	url(r'^ini5/$',views.Initiate5View.as_view(),name='ini5'),
	url(r'^ini6/$',views.Initiate6View.as_view(),name='ini6'),
	# 用户中心
	url(r'^info/$',views.UserInfo.as_view(),name='info'),
	url(r'^mine/$',views.MyDevious.as_view(),name='mine'),
	url(r'^real/$',views.RealName.as_view(),name='real'),

]

devious/project/models.py
from django.db import models
from datetime import datetime


# Create your models here.


class Tag(models.Model):
	name = models.CharField(max_length=100, verbose_name='类别名称')

	class Meta:
		verbose_name = '项目类别'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name


class Project(models.Model):
	name = models.CharField(max_length=255, verbose_name='项目名称')
	desc = models.CharField(max_length=255, verbose_name='项目描述')
	follower = models.IntegerField(verbose_name='关注人数', default=0)
	money = models.BigIntegerField(verbose_name='钱')
	supportmoney = models.BigIntegerField(verbose_name='支持的金额', null=True, default=0)
	time = models.IntegerField(verbose_name='筹集时间', null=True)
	date = models.DateField(verbose_name='截止日期')
	image1 = models.ImageField(max_length=200, upload_to='image/%Y/%m', verbose_name='项目图片1', null=True)
	image2 = models.ImageField(max_length=200, upload_to='image/%Y/%m', verbose_name='项目图片2', null=True)
	status = models.SmallIntegerField(default=0, choices=((0, '即将开始'), (1, '众筹中'), (2, '众筹成功'), (3, '众筹失败')),
									  verbose_name='项目状态')
	createdate = models.DateField(verbose_name='创建项目的时间', default=datetime.now)
	supporter = models.IntegerField(verbose_name='支持人数', null=True, default=0)
	tag = models.ForeignKey(Tag, verbose_name='类别')
	company = models.ForeignKey('Company', null=True)
	returns = models.CharField(max_length=255, verbose_name='回报内容', null=True)
	tags = models.CharField(max_length=100, verbose_name='项目标签', null=True)

	class Meta:
		verbose_name = '众筹项目'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name

	def get_time(self):
		endtime = self.date.strftime('%Y-%m_%d')
		endtime = datetime.strptime(endtime, '%Y-%m_%d')
		now = datetime.now().strftime('%Y-%m_%d')
		now = datetime.strptime(now, '%Y-%m_%d')

		left_time = (endtime - now).days
		if left_time > 0:
			self.status = 1
		elif left_time <= 0:
			if self.supportmoney >= self.money:
				self.status = 2
			else:
				self.status = 3
		return left_time


# 公司
class Company(models.Model):
	name = models.CharField(max_length=60, verbose_name='公司名称')
	desc = models.CharField(max_length=255, verbose_name='公司简介')
	c_phone = models.CharField(max_length=20, verbose_name='电话', null=True)
	phone = models.IntegerField(verbose_name='客服电话')
	image = models.ImageField(upload_to='company/%Y/%m', null=True, verbose_name='公司图片')
	aut = models.CharField(max_length=100, choices=((('0', '未认证'), ('1', '已认证'))), verbose_name='认证状态', default='0',
						   null=True)

	class Meta:
		verbose_name = '公司名称'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name

# 发票
class Invoice(models.Model):
	types = models.CharField(choices=(('0', '无发票'), ('1', '个人发票'), ('2', '自定义发票')), verbose_name='发票', max_length=20)

	def __str__(self):
		return 'Invoice'


class ReturnGoods(models.Model):
	project = models.ForeignKey(Project, verbose_name='项目名称')
	type = models.CharField(max_length=20, choices=(('0', '实物回报'), ('1', '虚拟物品回报')), verbose_name='回报类型', default='0')
	desc = models.CharField(max_length=100, verbose_name='回报简述', null=True)
	image = models.ImageField(upload_to='return/%Y/%m', verbose_name='回报图片', null=True)
	number = models.IntegerField(verbose_name='回报数量', null=True)
	pay_money = models.BigIntegerField(verbose_name='支付金额')
	palces = models.CharField(max_length=10, verbose_name='名额', default='无限制')
	limit_purch = models.CharField(max_length=20, verbose_name='单笔限购', default='不限购')
	return_goods_time = models.IntegerField(verbose_name='回报时间')
	freight = models.IntegerField(default=0, verbose_name='运费')
	invoice = models.CharField(max_length=20, choices=(('0', '无发票'), ('1', '个人发票'), ('2', '自定义发票')), verbose_name='发票')

	class Meta:
		verbose_name = '回报'
		verbose_name_plural = verbose_name

	def __str__(self):
		return 'aaa'


class Label(models.Model):
	name = models.CharField(max_length=20, verbose_name='标签名字')
	project = models.ForeignKey(Project, verbose_name='项目名称', null=True)

	class Meta:
		verbose_name = '标签'
		verbose_name_plural = verbose_name

	def __str__(self):
		return self.name

devious/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="utf-8">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>众筹网</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/carousel.css' %}">
    {% block extra_css %}{% endblock extra_css %}
    <style>
        h3 {
            font-weight: bold;
        }

        #footer {
            padding: 15px 0;
            background: #fff;
            border-top: 1px solid #ddd;
            text-align: center;
        }

        #topcontrol {
            color: #fff;
            z-index: 99;
            width: 30px;
            height: 30px;
            font-size: 20px;
            background: #222;
            position: relative;
            right: 14px !important;
            bottom: 11px !important;
            border-radius: 3px !important;
        }

        #topcontrol:after {
            /*top: -2px;*/
            left: 8.5px;
            content: "\f106";
            position: absolute;
            text-align: center;
            font-family: FontAwesome;
        }

        #topcontrol:hover {
            color: #fff;
            background: #18ba9b;
            -webkit-transition: all 0.3s ease-in-out;
            -moz-transition: all 0.3s ease-in-out;
            -o-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
        }

        /* 侧栏导航 */
        .sideBox {
            padding: 10px;
            height: 220px;
            background: #fff;
            margin-bottom: 10px;
            overflow: hidden;
        }

        .sideBox .hd {
            height: 30px;
            line-height: 30px;
            background: #f60;
            padding: 0 10px;
            text-align: center;
            overflow: hidden;
        }

        .sideBox .hd .more {
            color: #fff;
        }

        .sideBox .hd h3 span {
            font-weight: bold;
            font-size: 14px;
            color: #fff;
        }

        .sideBox .bd {
            padding: 5px 0 0;
        }

        #sideMenu .bd li {
            margin-bottom: 2px;
            height: 30px;
            line-height: 30px;
            text-align: center;
            overflow: hidden;
        }

        #sideMenu .bd li a {
            display: block;
            background: #EAE6DD;
        }

        #sideMenu .bd li a:hover {
            background: #D5CFBF;
        }

        /* 列表页 */
        #mainBox {
            margin-bottom: 10px;
            padding: 10px;
            background: #fff;
            overflow: hidden;
        }

        #mainBox .mHd {
            border-bottom: 2px solid #09c;
            height: 30px;
            line-height: 30px;
        }

        #mainBox .mHd h3 {
            display: initial;
            *display: inline;
            zoom: 1;
            padding: 0 15px;
            background: #09c;
            color: #fff;
        }

        #mainBox .mHd h3 span {
            color: #fff;
            font-size: 14px;
            font-weight: bold;
        }

        #mainBox .path {
            float: right;
        }

        /* 位置导航 */
        .path {
            height: 30px;
            line-height: 30px;
            padding-left: 10px;
        }

        .path a, .path span {
            margin: 0 5px;
        }

        /* 文章列表 */
        .newsList {
            padding: 10px;
            text-align: left;
        }

        .newsList li {
            background: url("../images/share/point.png") no-repeat 2px 14px;
            padding-left: 10px;
            height: 30px;
            line-height: 30px;
        }

        .newsList li a {
            display: inline-block;
            *display: inline;
            zoom: 1;
            font-size: 14px;
        }

        .newsList li .date {
            float: right;
            color: #999;
        }

        .newsList li.split {
            margin-bottom: 10px;
            padding-bottom: 10px;
            border-bottom: 1px dotted #ddd;
            height: 0px;
            line-height: 0px;
            overflow: hidden;
        }

        /* 通用带图片的信息列表_普通式 */
        .picList {
            padding: 10px;
            text-align: left;
        }

        .picList li {
            margin: 0 5px;
            height: 190px;
        }

        h3.break {
            font-size: 16px;
            display: block;
            white-space: nowrap;
            word-wrap: normal;
            overflow: hidden;
            text-overflow: ellipsis;
        }

        h3.break > a {
            text-decoration: none;
        }

    </style>
</head>
<body>
<div class="navbar-wrapper">
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'users:index' %}" style="font-size:32px;">尚筹网-创意产品众筹平台</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse" style="float:right;">
                    {% block log %}
                        <ul class="nav navbar-nav">
                            {% if request.user.is_authenticated %}
                                <li class="dropdown">
                                    <a href=" " class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i> {{ user.username }}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'users:info' %}"><i class="glyphicon glyphicon-scale"></i> 会员中心</a></li>
                                    <li><a href="#"><i class="glyphicon glyphicon-comment"></i> 消息 </a></li>
                                    <li class="divider"></li>
                                    <li><a href="{% url 'users:logout' %}"><i class="glyphicon glyphicon-off"></i> 退出系统</a></li>
                                </ul>
                                </li>
                            {% else %}
                                <div id="navbar" class="navbar-collapse collapse" style="float:right;">
                                    <ul class="nav navbar-nav navbar-right">
                                        <li><a href="{% url 'users:login' %}">登录</a></li>
                                        <li><a href="{% url 'users:register' %}">注册</a></li>
                                    </ul>
                                </div>
                            {% endif %}
                        </ul>
                    {% endblock log %}
                </div>
            </div>
        </nav>

    </div>
    {% block contain %}
    {% endblock contain %}
</div>

{% block content %}

{% endblock content %}
{% block footer %}
    <!-- FOOTER -->
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column">
                <div id="footer">
                    <div class="footerNav">
                        <a rel="nofollow" href="http://www.atguigu.com">关于我们</a> | <a rel="nofollow"
                                                                                      href="http://www.atguigu.com">服务条款</a>
                        | <a rel="nofollow" href="http://www.atguigu.com">免责声明</a> | <a rel="nofollow"
                                                                                        href="http://www.atguigu.com">网站地图</a>
                        | <a rel="nofollow" href="http://www.atguigu.com">联系我们</a>
                    </div>
                    <div class="copyRight">
                        Copyright ?2017-2017atguigu.com 版权所有
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock footer %}
</div><!-- /.container -->



{% block extra_js %}
    <script src="{% static 'jquery/jquery-2.1.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'script/docs.min.js' %}"></script>
    <script src="{% static 'script/back-to-top.js' %}"></script>
    <script>

        $(".thumbnail img").css("cursor", "pointer");
        $(".thumbnail img").click(function () {
            window.location.href = "project.html";
        });
    </script>
{% endblock extra_js %}
</body>
</html>

devious/templates/m_base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/css/font-awesome.min.css">
	<link rel="stylesheet" href="/static/css/theme.css">
      {% block extrac_style %}

      {% endblock extrac_style %}
  </head>
  <body>
 <div class="navbar-wrapper">
      <div class="navbar-wrapper">
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'users:index' %}" style="font-size:32px;">尚筹网-创意产品众筹平台</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse" style="float:right;">
                    {% block log %}
                        <ul class="nav navbar-nav">
                            {% if request.user.is_authenticated %}
                                <li class="dropdown">
                                    <a href=" " class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i> {{ user.username }}<span class="caret"></span></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="{% url 'users:info' %}"><i class="glyphicon glyphicon-scale"></i> 会员中心</a></li>
                                    <li><a href="#"><i class="glyphicon glyphicon-comment"></i> 消息 </a></li>
                                    <li class="divider"></li>
                                    <li><a href="{% url 'users:logout' %}"><i class="glyphicon glyphicon-off"></i> 退出系统</a></li>
                                </ul>
                                </li>
                            {% else %}
                                <div id="navbar" class="navbar-collapse collapse" style="float:right;">
                                    <ul class="nav navbar-nav navbar-right">
                                        <li><a href="{% url 'users:login' %}">登录</a></li>
                                        <li><a href="{% url 'users:register' %}">注册</a></li>
                                    </ul>
                                </div>
                            {% endif %}
                        </ul>
                    {% endblock log %}
                </div>
            </div>
        </nav>

    </div>
    {% block contain %}
    {% endblock contain %}
</div>
    </div>
<div class="container">
	<div class="row clearfix">
		<div class="col-sm-3 col-md-3 column">
			<div class="row">
				<div class="col-md-12">
					<div class="thumbnail" style="    border-radius: 0px;">
						<img src="img/services-box1.jpg" class="img-thumbnail" alt="">
						<div class="caption" style="text-align:center;">
							<h3>
								{{ request.user.username }}
							</h3>
							<span class="label label-danger" style="cursor:pointer;" onclick="window.location.href='{% url 'users:real' %}'">未实名认证</span>
						</div>
					</div>
				</div>
			</div>
			<div class="list-group">
				<div class="list-group-item {% ifequal request.path|slice:'5' '/info' %}active{% endifequal %}" style="cursor:pointer;" onclick="window.location.href='{% url 'users:info' %}'">
					资产总览<span class="badge"><i class="glyphicon glyphicon-chevron-right"></i></span>
				</div>
				<div class="list-group-item {% ifequal request.path|slice:'5' '/mine' %}active{% endifequal %}" style="cursor:pointer;" onclick="window.location.href='{% url 'users:mine' %}'">
					我的众筹<span class="badge"><i class="glyphicon glyphicon-chevron-right"></i></span>
				</div>
			</div>
		</div>
        {% block content %}

        {% endblock content %}
	</div>
</div>
        <div class="container" style="margin-top:20px;">
            <div class="row clearfix">
                <div class="col-md-12 column">
                    <div id="footer">
                        <div class="footerNav">
                             <a rel="nofollow" href="http://www.atguigu.com">关于我们</a> | <a rel="nofollow" href="http://www.atguigu.com">服务条款</a> | <a rel="nofollow" href="http://www.atguigu.com">免责声明</a> | <a rel="nofollow" href="http://www.atguigu.com">网站地图</a> | <a rel="nofollow" href="http://www.atguigu.com">联系我们</a>
                        </div>
                        <div class="copyRight">
                            Copyright ?2017-2017atguigu.com 版权所有
                        </div>
                    </div>

                </div>
            </div>
        </div>
    <script src="/static/jquery/jquery-2.1.1.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
	<script src="/static/script/docs.min.js"></script>
    <script src="/static/script/back-to-top.js"></script>
    <script src="/static/script/echarts.js"></script>
	<script>
$('#myTab a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})
$('#myTab1 a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})

        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
option = {
    title: {
        text: '七日年化收益率(%)'
    },
    tooltip: {
        trigger: 'axis'
    },
    legend: {
        data:['基金','股票']
    },
    toolbox: {
        show: false,
        feature: {
            dataZoom: {
                yAxisIndex: 'none'
            },
            dataView: {readOnly: false},
            magicType: {type: ['line', 'bar']},
            restore: {},
            saveAsImage: {}
        }
    },
    xAxis:  {
        type: 'category',
        boundaryGap: false,
        data: ['2017-05-16','2017-05-17','2017-05-18','2017-05-19','2017-05-20','2017-05-21','2017-05-22']
    },
    yAxis: {
        type: 'value',
        axisLabel: {
            formatter: '{value} '
        }
    },
    series: [
        {
            name:'基金',
            type:'line',
            data:[1, 1, 5, 3, 2, 3, 2],
            markPoint: {
                data: [
                    {type: 'max', name: '最大值'},
                    {type: 'min', name: '最小值'}
                ]
            },
            markLine: {
                data: [
                    {type: 'average', name: '平均值'}
                ]
            }
        },
        {
            name:'股票',
            type:'line',
            data:[1, -2, 2, 5, 3, 2, 4],
            markPoint: {
                data: [
                    {name: '周最低', value: -2, xAxis: 1, yAxis: -1.5}
                ]
            },
            markLine: {
                data: [
                    {type: 'average', name: '平均值'},
                    [{
                        symbol: 'none',
                        x: '90%',
                        yAxis: 'max'
                    }, {
                        symbol: 'circle',
                        label: {
                            normal: {
                                position: 'start',
                                formatter: '最大值'
                            }
                        },
                        type: 'max',
                        name: '最高点'
                    }]
                ]
            }
        }
    ]
};
myChart.setOption(option);
        var myChart1 = echarts.init(document.getElementById('main1'));

        // 指定图表的配置项和数据
option1 = {
    color: ['#3398DB'],
    tooltip : {
        trigger: 'axis',
        axisPointer : {            // 坐标轴指示器，坐标轴触发有效
            type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
        }
    },
    grid: {
        left: '3%',
        right: '4%',
        bottom: '3%',
        containLabel: true
    },
    xAxis : [
        {
            type : 'category',
            data : ['基金', '票据', '定期理财', '变现贷'],
            axisTick: {
                alignWithLabel: true
            }
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'直接访问',
            type:'bar',
            barWidth: '60%',
            data:[10, 52, 200, 334, 390, 330, 220]
        }
    ]
};

        // 使用刚指定的配置项和数据显示图表。
        myChart1.setOption(option1);

        var myChart2 = echarts.init(document.getElementById('main2'));

        // 指定图表的配置项和数据
option2 = {
    title : {
        text: '某站点用户访问来源',
        subtext: '纯属虚构',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient: 'vertical',
        left: 'left',
        data: ['直接访问','邮件营销','联盟广告','视频广告','搜索引擎']
    },
    series : [
        {
            name: '访问来源',
            type: 'pie',
            radius : '55%',
            center: ['50%', '60%'],
            data:[
                {value:335, name:'直接访问'},
                {value:310, name:'邮件营销'},
                {value:234, name:'联盟广告'},
                {value:135, name:'视频广告'},
                {value:1548, name:'搜索引擎'}
            ],
            itemStyle: {
                emphasis: {
                    shadowBlur: 10,
                    shadowOffsetX: 0,
                    shadowColor: 'rgba(0, 0, 0, 0.5)'
                }
            }
        }
    ]
};

        // 使用刚指定的配置项和数据显示图表。
        myChart2.setOption(option2);
	</script>
  <script>
console.log({{ request.url }})
</script>
  </body>
</html>

devious/templates/p_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="utf-8">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>众筹网</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">

        {% block extra_style %}
        {% endblock extra_style %}

</head>
<body>
<div class="navbar-wrapper">
    <div class="container">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'users:index' %}" style="font-size:32px;">互联网众筹系统</a>
                </div>
                <div id="navbar" class="navbar-collapse collapse" style="float:right;">
                    {% block log %}
                        <ul class="nav navbar-nav">
                            {% if request.user.is_authenticated %}
                                <li class="dropdown">
                                    <a href=" " class="dropdown-toggle" data-toggle="dropdown"><i
                                            class="glyphicon glyphicon-user"></i> {{ user.username }}<span
                                            class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="{% url 'users:info' %}"><i class="glyphicon glyphicon-scale"></i> 会员中心</a>
                                        </li>
                                        <li><a href="#"><i class="glyphicon glyphicon-comment"></i> 消息 </a></li>
                                        <li class="divider"></li>
                                        <li><a href="{% url 'users:logout' %}"><i class="glyphicon glyphicon-off"></i>
                                            退出系统</a></li>
                                    </ul>
                                </li>
                            {% else %}
                                <div id="navbar" class="navbar-collapse collapse" style="float:right;">
                                    <ul class="nav navbar-nav navbar-right">
                                        <li><a href="{% url 'users:login' %}">登录</a></li>
                                        <li><a href="{% url 'users:register' %}">注册</a></li>
                                    </ul>
                                </div>
                            {% endif %}
                        </ul>
                    {% endblock log %}
                </div>
            </div>
        </nav>
    </div>
</div>

<div class="container theme-showcase" role="main">

    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column">
                <nav class="navbar navbar-default" role="navigation">
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li>
                                <a rel="nofollow" href="{% url 'users:index' %}"><i class="glyphicon glyphicon-home"></i> 众筹首页</a>
                            </li>
                            <li class="active">
                                <a rel="nofollow" href="{% url 'project:list' %}"><i class="glyphicon glyphicon-th-large"></i> 项目总览</a>
                            </li>
                            <li>
                                <a rel="nofollow" href="{% url 'users:ini1' %}"><i class="glyphicon glyphicon-edit"></i> 发起众筹</a>
                            </li>
                            <li>
                                <a rel="nofollow" href="#"><i class="glyphicon glyphicon-user"></i>
                                    我的众筹</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
{% block content %}
{% endblock content %}

    <div class="container" style="margin-top:20px;">
        <div class="row clearfix">
            <div class="col-md-12 column">
                <div id="footer">
                    <div class="footerNav">
                        <a rel="nofollow" href="http://www.atguigu.com">关于我们</a> | <a rel="nofollow"
                                                                                      href="http://www.atguigu.com">服务条款</a>
                        | <a rel="nofollow" href="http://www.atguigu.com">免责声明</a> | <a rel="nofollow"
                                                                                        href="http://www.atguigu.com">网站地图</a>
                        | <a rel="nofollow" href="http://www.atguigu.com">联系我们</a>
                    </div>
                    <div class="copyRight">
                        Copyright ?2010-2014atguigu.com 版权所有
                    </div>
                </div>

            </div>
        </div>
    </div>

</div> <!-- /container -->
<script src="{% static 'jquery/jquery-2.1.1.min.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'script/docs.min.js' %}"></script>
<script src="{% static 'script/back-to-top.js' %}"></script>
<script>
    $('#myTab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show')
    })
</script>
{% block extra_js %}
{% endblock extra_js %}
</body>
</html>